version: '3'

services:

  db:
    image: postgis/postgis:latest
    container_name: geoapp_postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=geoapp
      - POSTGRES_DB=geoapp
      - POSTGRES_USER=geoapp
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  web:
    build: .
    container_name: geoapp_web
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_PASSWORD=geoapp
      - POSTGRES_DB=geoapp
      - POSTGRES_USER=geoapp
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: