# Generated by Django 3.0.9 on 2021-03-01 00:01

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=location_field.models.spatial.LocationField(srid=4326),
        ),
    ]
