# Generated by Django 3.0.9 on 2021-03-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_auto_20210301_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
